# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Canary"
license = "GPLv3"
licenselink = "https://github.com/c-edw/canary/blob/master/LICENSE"
description = "A simple theme inspired by Cocoa."
homepage = "https://github.com/c-edw/canary"
tags = ["simple", "clean", "modern", "chroma", "blog"]
features = ["chroma", "blog"]
min_version = "0.53"

[author]
  name = "Connor E."
  homepage = "https://github.com/c-edw"
